//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietHolderClient.ServiceReferenceCaloriesCalculator {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/DietHolderServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DailyActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoalToRealizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KindOfPostureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DailyActivity {
            get {
                return this.DailyActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.DailyActivityField, value) != true)) {
                    this.DailyActivityField = value;
                    this.RaisePropertyChanged("DailyActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoalToRealize {
            get {
                return this.GoalToRealizeField;
            }
            set {
                if ((object.ReferenceEquals(this.GoalToRealizeField, value) != true)) {
                    this.GoalToRealizeField = value;
                    this.RaisePropertyChanged("GoalToRealize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KindOfPosture {
            get {
                return this.KindOfPostureField;
            }
            set {
                if ((object.ReferenceEquals(this.KindOfPostureField, value) != true)) {
                    this.KindOfPostureField = value;
                    this.RaisePropertyChanged("KindOfPosture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calorify", Namespace="http://schemas.datacontract.org/2004/07/DietHolderServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Calorify : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CaloriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Calories {
            get {
                return this.CaloriesField;
            }
            set {
                if ((this.CaloriesField.Equals(value) != true)) {
                    this.CaloriesField = value;
                    this.RaisePropertyChanged("Calories");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCaloriesCalculator.ICaloriesCalculator")]
    public interface ICaloriesCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaloriesCalculator/GetBmrValue", ReplyAction="http://tempuri.org/ICaloriesCalculator/GetBmrValueResponse")]
        double GetBmrValue(DietHolderClient.ServiceReferenceCaloriesCalculator.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaloriesCalculator/GetBmrValue", ReplyAction="http://tempuri.org/ICaloriesCalculator/GetBmrValueResponse")]
        System.Threading.Tasks.Task<double> GetBmrValueAsync(DietHolderClient.ServiceReferenceCaloriesCalculator.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaloriesCalculator/GetDailyCaloriesToEatValue", ReplyAction="http://tempuri.org/ICaloriesCalculator/GetDailyCaloriesToEatValueResponse")]
        double GetDailyCaloriesToEatValue(DietHolderClient.ServiceReferenceCaloriesCalculator.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaloriesCalculator/GetDailyCaloriesToEatValue", ReplyAction="http://tempuri.org/ICaloriesCalculator/GetDailyCaloriesToEatValueResponse")]
        System.Threading.Tasks.Task<double> GetDailyCaloriesToEatValueAsync(DietHolderClient.ServiceReferenceCaloriesCalculator.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaloriesCalculator/GetMacrosDistribution", ReplyAction="http://tempuri.org/ICaloriesCalculator/GetMacrosDistributionResponse")]
        System.Collections.Generic.Dictionary<string, double> GetMacrosDistribution(DietHolderClient.ServiceReferenceCaloriesCalculator.Calorify kalorie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaloriesCalculator/GetMacrosDistribution", ReplyAction="http://tempuri.org/ICaloriesCalculator/GetMacrosDistributionResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, double>> GetMacrosDistributionAsync(DietHolderClient.ServiceReferenceCaloriesCalculator.Calorify kalorie);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICaloriesCalculatorChannel : DietHolderClient.ServiceReferenceCaloriesCalculator.ICaloriesCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CaloriesCalculatorClient : System.ServiceModel.ClientBase<DietHolderClient.ServiceReferenceCaloriesCalculator.ICaloriesCalculator>, DietHolderClient.ServiceReferenceCaloriesCalculator.ICaloriesCalculator {
        
        public CaloriesCalculatorClient() {
        }
        
        public CaloriesCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CaloriesCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaloriesCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaloriesCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetBmrValue(DietHolderClient.ServiceReferenceCaloriesCalculator.Person person) {
            return base.Channel.GetBmrValue(person);
        }
        
        public System.Threading.Tasks.Task<double> GetBmrValueAsync(DietHolderClient.ServiceReferenceCaloriesCalculator.Person person) {
            return base.Channel.GetBmrValueAsync(person);
        }
        
        public double GetDailyCaloriesToEatValue(DietHolderClient.ServiceReferenceCaloriesCalculator.Person person) {
            return base.Channel.GetDailyCaloriesToEatValue(person);
        }
        
        public System.Threading.Tasks.Task<double> GetDailyCaloriesToEatValueAsync(DietHolderClient.ServiceReferenceCaloriesCalculator.Person person) {
            return base.Channel.GetDailyCaloriesToEatValueAsync(person);
        }
        
        public System.Collections.Generic.Dictionary<string, double> GetMacrosDistribution(DietHolderClient.ServiceReferenceCaloriesCalculator.Calorify kalorie) {
            return base.Channel.GetMacrosDistribution(kalorie);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, double>> GetMacrosDistributionAsync(DietHolderClient.ServiceReferenceCaloriesCalculator.Calorify kalorie) {
            return base.Channel.GetMacrosDistributionAsync(kalorie);
        }
    }
}
